apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportail-auth
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: myportail
  template:
    metadata:
      labels:
        app: myportail
        service: auth
    spec:
      containers:
        - name: auth
          image: myportail/auth-service:1.0.11
          workingDir: /authService
          command: ["dotnet", "authService.dll"]
          resources:
            limits:
              memory: "250M"
              cpu: "0.5"
          ports:
            - containerPort: 8001
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: authdbsecrets
                  key: authdb.connection.user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authdbsecrets
                  key: authdb.connection.password
      restartPolicy: Always
