apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: {{ .Values.namespace }}
  labels:
    app: myportail
    service: authservice
spec:
  type: NodePort
  ports:
    - port: 8001
      name: mariadb
      targetPort: 8001
      nodePort: 30101
  selector:
    app: myportail
    service: auth
