apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: {{ .Values.namespace }}
  labels:
    app: myportail
    service: authservice
spec:
  type: NodePort
  ports:
    - port: 80
      name: authservice-http
      targetPort: 80
      nodePort: 30101
    - port: 443
      name: authservice-https
      targetPort: 443
      nodePort: 30102
  selector:
    app: myportail
    service: auth
