apiVersion: v1
kind: Secret
metadata:
  name: authdbsecrets
  namespace: {{ .Values.namespace }}
stringData:
  mysqlrootpassword: password123
  authdb.user: authservice
  authdb.password: igQFUwjZZyxgken7gcKg*gTu

