apiVersion: v1
kind: Secret
metadata:
  name: authdbsecrets
  namespace: {{ .Values.namespace }}
stringData:
  authdb.connection.rootpassword: password123
  authdb.connection.user: authservice
  authdb.connection.password: igQFUwjZZyxgken7gcKg*gTu

