apiVersion: v1
kind: Secret
metadata:
  name: authdbsecrets
  namespace: {{ .Values.namespace }}
stringData:
  mysqlusername: authservice
  mysqlpassword: igQFUwjZZyxgken7gcKg*gTu
  mysqlrootpassword: password123

