apiVersion: v1
kind: Secret
metadata:
  name: authdbsecrets
  namespace: {{ .Values.namespace }}
stringData:
  authdb.connection.rootpassword: password123
  authdb.connection.user: authservice
  authdb.connection.password: igQFUwjZZyxgken7gcKg*gTu

---

apiVersion: v1
kind: Secret
metadata:
  name: defaultuser-secrets
  namespace: {{ .Values.namespace }}
stringData:
  defaultuser.username: Admin
  defaultuser.password: Admin@123
