apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: loki
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/enable-rewrite-log: 'true'
    nginx.ingress.kubernetes.io/proxy-pass-request-headers: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/service-upstream: 'true'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/websocket-services: core-service
    nginx.org/websocket-services: core-service
spec:
  rules:
    - host: loki.danny-thibaudeau.ca
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: loki-grafana
              servicePort: 80
          - path: /
            backend:
              serviceName: loki-grafana
              servicePort: 80
