
apiVersion: batch/v1
kind: Job
metadata:
  name: myportail-authinit
spec:
  template:
    metadata:
      labels:
        app: myportail
        service: authenticationinit
    spec:
      containers:
        - name: authenticationinit
          image: myportail/authentication-init:latest
          workingDir: /authInit
          command: ["dotnet", "authInit.dll"]
      restartPolicy: Never
