version: '2'

services:
  auth-service:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    image: auth-service
    image: cobreti/myportail-auth-service:latest
    container_name: authservice
    working_dir: /authService
    entrypoint: ["dotnet", "authService.dll"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
#    networks:
#      - auth-db_authService
#      - portail
    ports:
      - "8001:8001"
#    external_links:
#      - authdb
#networks:
#  auth-db_authService:
#    external: true
#  portail:
#    external: true
